### ISSUE TITLE
Portability to OSX

### ISSUE THREAD

**Issue by dnbaker** [facebookresearch/flashlight#10]
flashlight requires the Gloo framework to build, but Gloo has explicitly stated that they do not support OSX because of the lack of epoll.

Do you plan to add support for OSX builds?

Thank you!

**Comment by vineelpratap** [comment]
Hi,
   Yes, we do want to support OSX builds. We plan to fallback and use standard MPI for distributed function calls if GLOO is not found. 

For now you can set `FL_BUILD_DISTRIBUTED ` to OFF so that you can try out flashlight. You can find more details about it here - https://fl.readthedocs.io/en/latest/installation.html#build-options

Also, note that if you want to build with CUDA backend, we support OSX and we have tested this.
