### ISSUE TITLE
Could NOT find CUDA (missing: CUDA_DIR)

### ISSUE THREAD

**Issue by saurabhhjjain** [facebookresearch/flashlight#24]
Hi
I am building flashlisght with CUDA backend. I have Centos 7, CUDA 10.0, nvcc 10.0. When I run cmake as : `cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BUILD_DISTRIBUTED=OFF` 

It gives following error :  

-- Could NOT find CUDA (missing: CUDA_DIR)
-- CUDA not found
CMake Error at CMakeLists.txt:114 (message):
  CUDA required to build CUDA backend

$PATH variable contains CUDA location. Can someone please tell me why I am getting this error ?

**Comment by jacobkahn** [comment]
@saurabhhjjain — CMake doesn't typically look at `$PATH` when locating dependencies. I'd have a look at [documentation for `FindCUDA`](https://cmake.org/cmake/help/v3.5/module/FindCUDA.html); it lists several flags you can pass to `cmake` to help it locate CUDA. I'd recommend setting `CUDA_TOOLKIT_ROOT_DIR` to the root directory of your CUDA installation (for example, on Linux-based systems, this is usually `/usr/local/cuda/`).

If you're still having trouble, I'd recommend Googling, since this isn't a flashlight-specific issue.
