### ISSUE TITLE
Combining CPU and GPU

### ISSUE THREAD

**Issue by danpovey** [facebookresearch/flashlight#32]
Guys, From CMakeLists.txt it looks like you compile Flashlight for a specific backend (CUDA or CPU, OPENCL), and there is reference to unified backend not being supported.

What does this mean in case, for instance, you wanted to set up something where some parts of the computation were done on GPU and some on CPU?

I sometimes have things I want to do where you need to do smallish computation that's very hard to implement on GPU (for instance, SVD), and it's the most efficient to just transfer it to CPU and do it there.  Is this kind of thing supported as-is?   I'd also like to understand to what extent Flashlight relies on ArrayFire for backend stuff (af::array operations), and what kinds of things it does itself.

**Comment by vineelpratap** [comment]
> I sometimes have things I want to do where you need to do smallish computation that's very hard to implement on GPU (for instance, SVD), and it's the most efficient to just transfer it to CPU and do it there. Is this kind of thing supported as-is?

We already support moving the arrays to CPU and doing the operations on host and moving back to GPU. `.host<..>()` can be used to move an array to CPU. For example the code here works for GPU arrays as well - https://git.io/fhH9I . 

> I'd also like to understand to what extent Flashlight relies on ArrayFire for backend stuff (af::array operations), and what kinds of things it does itself.

Apart from the obvious things like providing generic Modules, distributed API for training neural networks, Flashlight provides an efficient autograd API and implements the [autograd functions](https://git.io/fhH9m) either by making use of ArrayFire operations directly or using cuDNN/MKL-DNN etc.. with [ArrayFire's Interoperability](http://arrayfire.org/docs/interop_cuda.htm). Also, as mentioned [here](https://fl.readthedocs.io/en/latest/extend.html#writing-custom-kernels), it is easy to extend flashlight to use custom kernels instead of writing with just Arrayfire Operations.

**Comment by danpovey** [comment]
Hm.  I see that ArrayFire doesn't have a concept of arrays having individually specifiable backends (e.g. CPU vs. GPU, like the device in TensorFlow), so if you want to manually use CPU when the rest of the code uses GPU, you basically have to 'roll your own', as you have done with std::vector.  Not really ideal from my point of view.  I'll have to figure out how one might deal with this limitation.

**Comment by vineelpratap** [comment]
This can be done with Unified backend support #6 . We didn't prioritize this as it was not useful for our project [wav2letter](https://github.com/facebookresearch/wav2letter/) but it can done with little effort and minor modifications to codebase.

**Comment by danpovey** [comment]
Are you sure about this?  Because I looked around in the ArrayFire code and
it seems to me that what the unified codebase means is you call a global
function af_set_backend to set the backend to a new value, so that after
that, newly created arrays will be on the specified backend, but existing
arrays on a different backend won't be accessible.  Even if you could use
this, switching the backend back and forth and manually copying arrays from
device to host and back, to create mixed code, it looks very inconvenient
and would probably not be compatible with multi-threaded host code.


Dan

**Comment by vineelpratap** [comment]
> global function af_set_backend to set the backend to a new value, so that after that, newly created arrays will be on the specified backend, but existing arrays on a different backend won't be accessible

Yeah, that's true. We would have to manually switch backends.  

Since, we will be storing the arrays on CPU for SVD (let's say), we don't have to create a copy of the array to host. Also, looks like accessing different backends on different threads is [thread safe](https://groups.google.com/forum/#!topic/arrayfire-users/88xdRhdq87o) using unified API.

However, the API complexity using the unified backend will depend on the specific use case.

**Comment by danpovey** [comment]
OK, thanks.
