### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by danpovey** [facebookresearch/flashlight#39]
Guys, 
This is some design questions more than an 'issue' in the normal sense, that I'd be interested to hear your opinions on,

Let's suppose that instead of af::array you were using a class Tensor which you controlled, that implemented all the basic tensor functionality, and which had a fairly imperative interface (i.e. no expression-tree/jit magic happening behind the scenes).

In order to enable autograd, do you think would be better to just implement autograd by augmenting class Tensor itself with autograd machinery (so to get a plain old Tensor you would just set calcGrad = false)?  The Torch/PyTorch people seem to be moving in that direction, if I correctly understand their response to an issue I raised there, and I assume they must have reasons for that choice.  E.g. I suppose it avoids a bunch of indirection or wrapping, and it must avoid having to decide what to with mixed-type arguments.  Personally I feel like it would make the code harder to wrap one's head around, though (and might lead to unnecessary expensive atomic operatins with shared_ptr's).  LMK what you think about this.

A couple more specific questions about the autograd.

 - I notice your SharedGrad::grad is a pointer to Variable, not a plain old af::array.  Do you think it could possibly be a reasonable choice to just make the grad a plain old array/Tensor/whatever, assuming one controlled the interface of that type?  Flashlight doesn't support 2nd order derivatives, so I assume support for that is not the reason you made it a Variable rather than an af::array.   

  The above is separate from the choice of whether to expose the type array/Tensor in Python or whatever, if one was going to go in that direction. I can imagine that wrapping both array/Tensor and Variable at the python level, if one were to do that, might get to be a hassle, and I assume that's why PyTorch only exposes the C++ type Variable.   I just feel like it might be nice to have a separate Tensor class at the C++ level, with a simple interface where one doesn't have to worry about autograd issues. But the PyTorch people might see something that I don't.

 - Do you think it would be reasonable to consider, instead of giving SharedGrad a vector of Variable as inputs, to just give it a vector of shared_ptr<SharedGrad>?  And if the gradFunc needs access to any of the inputs, just pass them in using bound variables?  That would avoid the need for withoutData(), and might reduce the chance of ever running into reference cycles.

**Comment by vineelpratap** [comment]
Hi @danpovey, 

Regarding your questions - 

> Single Tensor vs af::array/fl::Variable

The main reason behind this choice was we wanted autograd should be built on top of tensor library and not in conjunction. Also, as you mentioned not everything is gradient based even when someone is working in NN world.

>  SharedGrad::grad is a pointer to Variable, not a plain old af::array

We don't support 2nd order derivative at the moment because we didn't have bandwidth to work on it. But we certainly want to extend it in future. So, using af::array will make the API break because we need to track the computation graph of gradient using Variable if we want to support 2nd order gradients. 


> giving SharedGrad a vector of Variable as inputs, to just give it a vector of shared_ptr

One of the main steps during backward pass is to create the computation graph in topologically sorted order using DFS - https://git.io/fjehN . This is important because we can have two outputs from a single input (for ex. multi-head network) and we need to traverse in correct order for efficiency. Further, there are only handful of cases when can use `withoutGrad` optimization.

**Comment by danpovey** [comment]
Re the last point, I think the DFS sorting could be done equally well if you gave the SharedGrad as inputs instead of the Variable.  But it's a small point.
