### ISSUE TITLE
Recommend version of dependencies when build from source

### ISSUE THREAD

**Issue by tranmanhdat** [facebookresearch/flashlight#392]
Im building flashlight from source, and confuse about version of dependencies ( CUDA, CuDNN, NCCL ..)
i found some issues about version CuDNN when build from source.
Any suggestion for version of dependencies?

OS: Ubuntu 18.04 LTS with nvidia card support

**Comment by jacobkahn** [comment]
Flashlight has been tested with CUDA > 9.2, but since you're using Ubuntu 18.04, you should use a newer version of CUDA if your GPU supports it. CUDA 10 or CUDA 11 should work fine.

As for cuDNN or NCCL, you need to make sure you use a version that's compatible with the CUDA version you've installed (they'll say which version they're compatible with), but besides that, the difference should be minimal; using later versions may lead to slightly better performance and will ensure improved support.
