### ISSUE TITLE
Too many malloc/free observed

### ISSUE THREAD

**Issue by minty99** [facebookresearch/flashlight#63]
![Screenshot at Jul 31 11-51-14](https://user-images.githubusercontent.com/3724119/62180097-a4e6ee80-b389-11e9-8196-364a72b68ecb.png)

I profiled a flashlight application using Linear, Conv2D, RNN (LSTM). I found too many malloc/free in the result.

Is this intended? How can I avoid this?

**Comment by jacobkahn** [comment]
@minty99 — this is most likely caused by ArrayFire's memory manager, which has a small step size (1kb) by default, meaning if your allocations have a large variance in sizes, you'll rarely reuse memory.

The best solution is probably to increase your step size using `af::setMemStepSize` ([example](https://git.io/fjSQl)) so you can make more similarly-sized allocations and more effectively reuse memory. This is also an active area of work for us and something we'll be improving very soon.

**Comment by minty99** [comment]
@jacobkahn - I tested your solution. But I found some weird result:
memstep size : consumed time of application
1k: 0.22 sec
8k: 0.22 sec
10k: 0.15 sec
16k: 0.22 sec
32k: 0.22 sec

Why only *10k* is faster? Is 10k a magic number for memstep size?

**Comment by jacobkahn** [comment]
@minty99 — these numbers look a bit odd because they're so consistent, but it's possible that a 10k step size creates different internal fragmentation. This will depend heavily on the size of the allocations fl is making, which will depend a lot on your architecture/input size. I'd continue to try even larger step sizes up to multiple MB (we use 8338608 for some of our seq2seq models, for instance).

**Comment by jacobkahn** [comment]
@minty99 — this is likely because of how the ArrayFire memory manager caches internal allocations. If you ask for similarly-sized `af:;array`s, ArrayFire will reuse previusly-allocated memory if possible, which will avoid calls to `cudaMalloc` and `cudaFree`.

**Comment by vineelpratap** [comment]
Hi,
 We have recently updated flashlight to a better memory manager and it should remove the issues you are facing.
